
- name: play level variables
  hosts: local
  connection: local

  vars_files:
  - course.yaml # getting variables from another files  

  tasks:
    name: variables
    vars:
      course: "Ansible" # This Course is task level it override the above course and variable and print this
    ansible.builtin.debug:
      msg: "course is {{course}}, platform is {{platform}}, trainer is {{trainer}}, duration is {{duration}}"  
